### ISSUE TITLE
0.x number

### ISSUE THREAD

**Issue by inomn** [lih1989/vue-input-calculator#1]
Привет с хабра.
В демке невозможноо ввести 0.1

**Comment by inomn** [comment]
двойной клик на точку дает ввести `0.1`
но нельзя ввести `0.1` `+` `0.1`
клик по точке после ввода 0.1 + дает `0.1.`

**Comment by lih1989** [comment]
> двойной клик на точку дает ввести `0.1`
> но нельзя ввести `0.1` `+` `0.1`
> клик по точке после ввода 0.1 + дает `0.1.`

Привет! Спасибо за  тестирование! Поправлю на днях

**Comment by lih1989** [comment]
Переписал парсер выражений и условия ввода
